update-interval-ticks: 1
check-updates: true
language: auto

#auto - automatically detects your language
#en - English
#ru - Russian
#uk - Ukrainian
#pl - Polish
#de - German

#         *        .        âœ¦          .             .         *
#        .                *        .         âœ·             âœ§        .
#               .        â‹†    *         âœ§         *      â‹†          .
#  â‹†           .        .        â‹†     .             â‹†       .     .
#        âœ·         .       *         âœ¦     â‹†      .     â‹†      *
# .      â‹†    â‹†        .         âœ§       â‹†     âœ¦           â‹†         âœ¦
#        .    â‹†         âœ·             â‹†          â‹†    âœ§      .      â‹†
# âœ·      .        â‹†     .    â‹†      â˜„       â‹†     .     â‹†     âœ§        .
#       .    âœ¦       .      â‹†       â‹†      âœ·        .        â‹†       .
#             â‹†        â‹†        âœ·           .         âœ¦      â‹†
#  â‹†    .       âœ¦       â‹†       .     ğ’·ğ“       âœ·        âœ¦        â‹†       âœ·
#       .         âœ·        â‹†        ğ“ˆğ“ğ“ğ“…ğ’½  .         âœ§    â‹†         â‹†
#   âœ·          .        .      â‹†  ğ’¾ğ“ƒ ï¼’ï¼ï¼’ï¼•  .             â‹†        .      .
#        .          â‹†    *         âœ¦         *      â‹†          .
#            .                *        .         âœ·             âœ§        .
#        âœ·         .       *         âœ¦     â‹†      .     â‹†      *
# .      â‹†    â‹†        .         âœ§       â‹†     âœ¦           â‹†         âœ¦
#        .    â‹†         âœ·             â‹†          â‹†    âœ§      .      â‹†
# âœ·      .        â‹†     .    â‹†      â˜„       â‹†     .     â‹†     âœ§        .
#       .    âœ¦       .      â‹†       â‹†      âœ·        .        â‹†      .
#             â‹†        â‹†        âœ·           .         âœ¦      â‹†
#         *        .        âœ¦          .             .         *